#import <WebGL/Types.idl>

// https://registry.khronos.org/webgl/specs/latest/1.0/#5.11
[Exposed=(Window,Worker)]
interface WebGLActiveInfo {
    [FIXME] readonly attribute GLint size;
    [FIXME] readonly attribute GLenum type;
    [FIXME] readonly attribute DOMString name;
};
