#import <DOM/Event.idl>

[Exposed=(Window,Worker)]
interface WebGLContextEvent : Event {
    constructor(DOMString type, optional WebGLContextEventInit eventInit = {});
    readonly attribute DOMString statusMessage;
};

dictionary WebGLContextEventInit : EventInit {
    DOMString statusMessage = "";
};
