// https://html.spec.whatwg.org/#canvaspattern
[Exposed=(Window,Worker)]
interface CanvasPattern {
    // opaque object
    [FIXME] undefined setTransform(optional DOMMatrix2DInit transform = {});
};
