#import <FileAPI/FileList.idl>
#import <HTML/DataTransferItemList.idl>

// https://html.spec.whatwg.org/multipage/dnd.html#datatransfer
[Exposed=Window]
interface DataTransfer {
    constructor();

    attribute DOMString dropEffect;
    attribute DOMString effectAllowed;

    [SameObject] readonly attribute DataTransferItemList items;

    [FIXME] undefined setDragImage(Element image, long x, long y);

    // old interface
    readonly attribute sequence<DOMString> types; // FIXME: This should be FrozenArray<DOMString>
    DOMString getData(DOMString format);
    [FIXME] undefined setData(DOMString format, DOMString data);
    [FIXME] undefined clearData(optional DOMString format);
    [SameObject] readonly attribute FileList files;
};
