// https://html.spec.whatwg.org/multipage/dnd.html#datatransfer
[Exposed=Window]
interface DataTransfer {
    constructor();

    [FIXME] attribute DOMString dropEffect;
    [FIXME] attribute DOMString effectAllowed;

    [FIXME, SameObject] readonly attribute DataTransferItemList items;

    [FIXME] undefined setDragImage(Element image, long x, long y);

    // old interface
    [FIXME] readonly attribute FrozenArray<DOMString> types;
    [FIXME] DOMString getData(DOMString format);
    [FIXME] undefined setData(DOMString format, DOMString data);
    [FIXME] undefined clearData(optional DOMString format);
    [FIXME, SameObject] readonly attribute FileList files;
};
