#import <FileAPI/File.idl>

callback FunctionStringCallback = undefined (DOMString data);

// https://html.spec.whatwg.org/multipage/dnd.html#datatransferitem
[Exposed=Window]
interface DataTransferItem {
    readonly attribute DOMString kind;
    readonly attribute DOMString type;
    [FIXME] undefined getAsString(FunctionStringCallback? _callback);
    File? getAsFile();
};
