#import <DOM/Document.idl>

enum DOMParserSupportedType {
    "text/html",
    "text/xml",
    "application/xml",
    "application/xhtml+xml",
    "image/svg+xml"
};

interface DOMParser {
    constructor();

    Document parseFromString(DOMString string, DOMParserSupportedType type);
};
