// https://html.spec.whatwg.org/#domstringmap
[Exposed=Window, LegacyOverrideBuiltIns]
interface DOMStringMap {
    getter DOMString (DOMString name);

    // FIXME: Extended attributes are currently not applied to special operations.
    [CEReactions] setter undefined (DOMString name, DOMString value);
    [CEReactions] deleter undefined (DOMString name);
};
