// https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#domstringlist
[Exposed=(Window,Worker)]
interface DOMStringList {
    readonly attribute unsigned long length;
    getter DOMString? item(unsigned long index);
    boolean contains(DOMString string);
};
