#import <DOM/Event.idl>

// https://html.spec.whatwg.org/#errorevent
[Exposed=(Window,Worker)]
interface ErrorEvent : Event {
    constructor(DOMString type, optional ErrorEventInit eventInitDict = {});

    readonly attribute DOMString message;
    readonly attribute USVString filename;
    readonly attribute unsigned long lineno;
    readonly attribute unsigned long colno;
    readonly attribute any error;
};

dictionary ErrorEventInit : EventInit {
    DOMString message = "";
    USVString filename = "";
    unsigned long lineno = 0;
    unsigned long colno = 0;
    any error = null;
};
