#import <DOM/Event.idl>

// https://html.spec.whatwg.org/multipage/nav-history-apis.html#hashchangeevent
[Exposed=Window]
interface HashChangeEvent : Event {
    constructor(DOMString type, optional HashChangeEventInit eventInitDict = {});

    readonly attribute USVString oldURL;
    readonly attribute USVString newURL;
};

dictionary HashChangeEventInit : EventInit {
    USVString oldURL = "";
    USVString newURL = "";
};
