#import <HTML/HTMLElement.idl>

interface HTMLMarqueeElement : HTMLElement {

    [Reflect] attribute DOMString behavior;
    [Reflect=bgcolor] attribute DOMString bgColor;
    [Reflect] attribute DOMString direction;
    [Reflect] attribute DOMString height;
    [Reflect] attribute DOMString width;

};
