#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/grouping-content.html#htmlhrelement
[Exposed=Window]
interface HTMLHRElement : HTMLElement {

    [Reflect] attribute DOMString align;
    [Reflect] attribute DOMString color;
    [Reflect=noshade] attribute boolean noShade;
    [Reflect] attribute DOMString size;
    [Reflect] attribute DOMString width;

};
