#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmloptionelement
[Exposed=Window, LegacyFactoryFunction=Option(optional DOMString text = "", optional DOMString value, optional boolean defaultSelected = false, optional boolean selected = false)]
interface HTMLOptionElement : HTMLElement {
    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute boolean disabled;
    readonly attribute HTMLFormElement? form;
    [CEReactions, Reflect] attribute DOMString label;
    [CEReactions, Reflect=selected] attribute boolean defaultSelected;
    attribute boolean selected;
    [CEReactions] attribute DOMString value;

    [CEReactions] attribute DOMString text;
    readonly attribute long index;
};
