module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLModElement.h";

interface HTMLModElement : HTMLElement {

    [Reflect] attribute DOMString cite;
    [Reflect=datetime] attribute DOMString dateTime;

};
