module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/HTML/HTMLOptionElement.h";

interface HTMLOptionElement : HTMLElement {

    [Reflect] attribute boolean disabled;
    [Reflect=selected] attribute boolean defaultSelected;

};
