#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/scripting.html#htmlslotelement
[Exposed=Window, UseDeprecatedAKString]
interface HTMLSlotElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString name;

};
