module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/HTML/HTMLSourceElement.h";

interface HTMLSourceElement : HTMLElement {

    [Reflect] attribute DOMString src;
    [Reflect] attribute DOMString type;
    [Reflect] attribute DOMString srcset;
    [Reflect] attribute DOMString sizes;
    [Reflect] attribute DOMString media;

};
