#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlbaseelement
[Exposed=Window]
interface HTMLBaseElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions] attribute USVString href;
    [CEReactions, Reflect] attribute DOMString target;

};
