#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/grouping-content.html#htmlquoteelement
[Exposed=Window]
interface HTMLQuoteElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect, URL] attribute USVString cite;

};
