#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlfontelement
[Exposed=Window]
interface HTMLFontElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, LegacyNullToEmptyString, Reflect] attribute DOMString color;
    [CEReactions, Reflect] attribute DOMString face;
    [CEReactions, Reflect] attribute DOMString size;

};
