#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlfieldsetelement
[Exposed=Window]
interface HTMLFieldSetElement : HTMLElement {

    readonly attribute DOMString type;

};
