#import <HTML/HTMLElement.idl>

interface HTMLMetaElement : HTMLElement {

    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString content;
    [Reflect=http-equiv] attribute DOMString httpEquiv;

    [Reflect] attribute DOMString scheme;

};
