#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlmetaelement
[Exposed=Window, UseDeprecatedAKString]
interface HTMLMetaElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString name;
    [CEReactions, Reflect] attribute DOMString content;
    [CEReactions, Reflect=http-equiv] attribute DOMString httpEquiv;

    [CEReactions, Reflect] attribute DOMString scheme;

};
