module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLCanvasElement.h";

interface HTMLCanvasElement : HTMLElement {

    CanvasRenderingContext2D? getContext(DOMString contextId);
    readonly attribute unsigned long width;
    readonly attribute unsigned long height;

};
