#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmldialogelement
[Exposed=Window]
interface HTMLDialogElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute boolean open;
    attribute DOMString returnValue;
    [CEReactions] undefined show();
    [CEReactions] undefined showModal();
    [CEReactions] undefined close(optional DOMString returnValue);

};
