module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/HTML/HTMLMediaElement.h";

interface HTMLMediaElement : HTMLElement {

    [Reflect] attribute DOMString src;

    [Reflect] attribute boolean autoplay;
    [Reflect] attribute boolean loop;

    [Reflect] attribute boolean controls;

};
