#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmloptionelement
[Exposed=Window,  LegacyFactoryFunction=Option(optional DOMString text = "", optional DOMString value, optional boolean defaultSelected = false, optional boolean selected = false), UseDeprecatedAKString]
interface HTMLOptionElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute boolean disabled;
    [CEReactions, Reflect=selected] attribute boolean defaultSelected;
    attribute boolean selected;
    [CEReactions] attribute DOMString value;

    [CEReactions] attribute DOMString text;
    readonly attribute long index;

};
