#import <CSS/CSSStyleSheet.idl>
#import <HTML/HTMLElement.idl>

interface HTMLStyleElement : HTMLElement {

    [Reflect] attribute DOMString media;

    [Reflect] attribute DOMString type;

    // FIXME: This should come from a LinkStyle mixin
    readonly attribute CSSStyleSheet? sheet;

};
