#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/grouping-content.html#htmlmenuelement
[Exposed=Window]
interface HTMLMenuElement : HTMLElement {

    [Reflect] attribute boolean compact;

};
