#import <HTML/HTMLElement.idl>

interface HTMLOListElement : HTMLElement {

    [Reflect] attribute boolean reversed;
    [Reflect] attribute DOMString type;

    [Reflect] attribute boolean compact;

};
