#import <HTML/HTMLElement.idl>
#import <HTML/HTMLHyperlinkElementUtils.idl>

// https://html.spec.whatwg.org/multipage/image-maps.html#htmlareaelement
[Exposed=Window]
interface HTMLAreaElement : HTMLElement {
    // FIXME: [HTMLConstructor] constructor();

    // FIXME: [CEReactions] attribute DOMString alt;
    // FIXME: [CEReactions] attribute DOMString coords;
    // FIXME: [CEReactions] attribute DOMString shape;
    // FIXME: [CEReactions] attribute DOMString target;
    // FIXME: [CEReactions] attribute DOMString download;
    // FIXME: [CEReactions] attribute USVString ping;
    // FIXME: [CEReactions] attribute DOMString rel;
    // FIXME: [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
    // FIXME: [CEReactions] attribute DOMString referrerPolicy;

    // Obsolete
    [Reflect=nohref] attribute boolean noHref;
};

HTMLAreaElement includes HTMLHyperlinkElementUtils;
