module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLTableSectionElement.h";

interface HTMLTableSectionElement : HTMLElement {

    [Reflect] attribute DOMString align;
    [Reflect=char] attribute DOMString ch;
    [Reflect=charoff] attribute DOMString chOff;
    [Reflect=valign] attribute DOMString vAlign;

};
