#import <HTML/HTMLElement.idl>
#import <HTML/HTMLFormElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmloutputelement
[Exposed=Window]
interface HTMLOutputElement : HTMLElement {
    [HTMLConstructor] constructor();

    [SameObject, PutForwards=value] readonly attribute DOMTokenList htmlFor;
    readonly attribute HTMLFormElement? form;
    [CEReactions, Reflect] attribute DOMString name;

    readonly attribute DOMString type;
    [CEReactions] attribute DOMString defaultValue;
    [CEReactions] attribute DOMString value;

    [FIXME] readonly attribute boolean willValidate;
    [FIXME] readonly attribute ValidityState validity;
    [FIXME] readonly attribute DOMString validationMessage;
    [FIXME] boolean checkValidity();
    [FIXME] boolean reportValidity();
    [FIXME] undefined setCustomValidity(DOMString error);

    readonly attribute NodeList labels;
};
