module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLOListElement.h";

interface HTMLOListElement : HTMLElement {

    [Reflect] attribute boolean reversed;
    [Reflect] attribute DOMString type;

    [Reflect] attribute boolean compact;

};
