#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/image-maps.html#htmlmapelement
[Exposed=Window, UseDeprecatedAKString]
interface HTMLMapElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString name;

};
