#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlheadingelement
[Exposed=Window]
interface HTMLHeadingElement : HTMLElement {

    [HTMLConstructor] constructor();

    // Obsolete
    [CEReactions, Reflect] attribute DOMString align;

};
