#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlheadelement
[Exposed=Window]
interface HTMLHeadElement : HTMLElement {

    [HTMLConstructor] constructor();

};
