#import <DOM/HTMLCollection.idl>
#import <HTML/HTMLElement.idl>

interface HTMLTableRowElement : HTMLElement {

    [Reflect] attribute DOMString align;
    [Reflect=char] attribute DOMString ch;
    [Reflect=charoff] attribute DOMString chOff;
    [Reflect=valign] attribute DOMString vAlign;

    [LegacyNullToEmptyString, Reflect=bgcolor] attribute DOMString bgColor;

    [SameObject] readonly attribute HTMLCollection cells;

};
