module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLFontElement.h";

interface HTMLFontElement : HTMLElement {

    [LegacyNullToEmptyString, Reflect] attribute DOMString color;
    [Reflect] attribute DOMString face;
    [Reflect] attribute DOMString size;

};
