#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmlprogresselement
[Exposed=Window]
interface HTMLProgressElement : HTMLElement {
    [HTMLConstructor] constructor();

    [CEReactions] attribute double value;
    [CEReactions] attribute double max;
    readonly attribute double position;
    readonly attribute NodeList labels;
};
