#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmldivelement
[Exposed=Window]
interface HTMLDivElement : HTMLElement {

    [Reflect] attribute DOMString align;

};
