#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/grouping-content.html#htmlhrelement
[Exposed=Window]
interface HTMLHRElement : HTMLElement {

    [HTMLConstructor] constructor();

    // Obsolete
    [CEReactions, Reflect] attribute DOMString align;
    [CEReactions, Reflect] attribute DOMString color;
    [CEReactions, Reflect=noshade] attribute boolean noShade;
    [CEReactions, Reflect] attribute DOMString size;
    [CEReactions, Reflect] attribute DOMString width;

};
