#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/dom.html#htmlunknownelement
[Exposed=Window]
interface HTMLUnknownElement : HTMLElement {

    // Note: intentionally no [HTMLConstructor]

};
