interface HTMLScriptElement : HTMLElement {

    [Reflect] attribute DOMString src;
    [Reflect] attribute DOMString type;
    [Reflect=nomodule] attribute boolean noModule;
    [Reflect] attribute boolean defer;
    [Reflect] attribute DOMString integrity;

    static boolean supports(DOMString type);

    [Reflect] attribute DOMString charset;
    [Reflect] attribute DOMString event;
    [Reflect=for] attribute DOMString htmlFor;

};
