#import <DOM/HTMLCollection.idl>
#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/tables.html#htmltablerowelement
[Exposed=Window]
interface HTMLTableRowElement : HTMLElement {

    [Reflect] attribute DOMString align;
    [Reflect=char] attribute DOMString ch;
    [Reflect=charoff] attribute DOMString chOff;
    [Reflect=valign] attribute DOMString vAlign;

    [LegacyNullToEmptyString, Reflect=bgcolor] attribute DOMString bgColor;

    readonly attribute long rowIndex;
    readonly attribute long sectionRowIndex;

    [SameObject] readonly attribute HTMLCollection cells;

};
