#import <HTML/HTMLElement.idl>

enum CanPlayTypeResult {
    "",
    "maybe",
    "probably"
};

// https://html.spec.whatwg.org/multipage/media.html#htmlmediaelement
[Exposed=Window]
interface HTMLMediaElement : HTMLElement {

    [Reflect, CEReactions] attribute DOMString src;

    [Reflect, CEReactions] attribute boolean autoplay;
    [Reflect, CEReactions] attribute boolean loop;

    [Reflect, CEReactions] attribute boolean controls;

    CanPlayTypeResult canPlayType(DOMString type);
    undefined load();
    undefined pause();
};
