#import <HTML/HTMLElement.idl>

interface HTMLParamElement : HTMLElement {

    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString value;

    [Reflect] attribute DOMString type;
    [Reflect=valuetype] attribute DOMString valueType;

};
