#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmldataelement
[Exposed=Window]
interface HTMLDataElement : HTMLElement {

    [Reflect] attribute DOMString value;

};
