#import <HTML/HTMLElement.idl>

interface HTMLProgressElement : HTMLElement {

    [CEReactions] attribute double value;
    [CEReactions] attribute double max;
    readonly attribute double position;

};
