#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmlmeterelement
[Exposed=Window]
interface HTMLMeterElement : HTMLElement {
    [HTMLConstructor] constructor();

    // FIXME: [CEReactions] attribute double value;
    // FIXME: [CEReactions] attribute double min;
    // FIXME: [CEReactions] attribute double max;
    // FIXME: [CEReactions] attribute double low;
    // FIXME: [CEReactions] attribute double high;
    // FIXME: [CEReactions] attribute double optimum;
    // FIXME: readonly attribute NodeList labels;
};
