#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmldatalistelement
[Exposed=Window]
interface HTMLDataListElement : HTMLElement {
    [HTMLConstructor] constructor();

    [SameObject] readonly attribute HTMLCollection options;
};
