#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/obsolete.html#htmlparamelement
[Exposed=Window]
interface HTMLParamElement : HTMLElement {

    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString value;

    [Reflect] attribute DOMString type;
    [Reflect=valuetype] attribute DOMString valueType;

};
