#import <DOM/HTMLCollection.idl>
#import <HTML/HTMLOptionElement.idl>
#import <HTML/HTMLOptGroupElement.idl>

// https://html.spec.whatwg.org/#htmloptionscollection
[Exposed=Window]
interface HTMLOptionsCollection : HTMLCollection {
    [CEReactions] attribute unsigned long length; // shadows inherited length
    // [CEReactions] setter undefined (unsigned long index, HTMLOptionElement? option);
    [CEReactions] undefined add((HTMLOptionElement or HTMLOptGroupElement) element, optional (HTMLElement or long)? before = null);
    [CEReactions] undefined remove(long index);
    attribute long selectedIndex;
};
