module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLButtonElement.h";

interface HTMLButtonElement : HTMLElement {

    [Reflect=formnovalidate] attribute boolean formNoValidate;
    [Reflect=formtarget] attribute DOMString formTarget;
    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString value;

};
