#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/image-maps.html#htmlmapelement
[Exposed=Window]
interface HTMLMapElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString name;
    [SameObject] readonly attribute HTMLCollection areas;

};
