module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/HTML/HTMLFrameSetElement.h";

interface HTMLFrameSetElement : HTMLElement {

    [Reflect] attribute DOMString cols;
    [Reflect] attribute DOMString rows;

};
