#import <DOM/HTMLCollection.idl>
#import <HTML/HTMLElement.idl>
#import <HTML/HTMLTableCellElement.idl>

// https://html.spec.whatwg.org/multipage/tables.html#htmltablerowelement
[Exposed=Window]
interface HTMLTableRowElement : HTMLElement {

    [HTMLConstructor] constructor();

    readonly attribute long rowIndex;
    readonly attribute long sectionRowIndex;
    [SameObject] readonly attribute HTMLCollection cells;
    HTMLTableCellElement insertCell(optional long index = -1);
    [CEReactions] undefined deleteCell(long index);

    // Obsolete
    [CEReactions, Reflect] attribute DOMString align;
    [CEReactions, Reflect=char] attribute DOMString ch;
    [CEReactions, Reflect=charoff] attribute DOMString chOff;
    [CEReactions, Reflect=valign] attribute DOMString vAlign;

    [CEReactions, LegacyNullToEmptyString, Reflect=bgcolor] attribute DOMString bgColor;

};
