// https://html.spec.whatwg.org/multipage/links.html#htmlhyperlinkelementutils
interface mixin HTMLHyperlinkElementUtils {
    [CEReactions] stringifier attribute USVString href;
    readonly attribute USVString origin;
    [CEReactions] attribute USVString protocol;
    [CEReactions] attribute USVString username;
    [CEReactions] attribute USVString password;
    [CEReactions] attribute USVString host;
    [CEReactions] attribute USVString hostname;
    [CEReactions] attribute USVString port;
    [CEReactions] attribute USVString pathname;
    [CEReactions] attribute USVString search;
    [CEReactions] attribute USVString hash;
};
