#import <HTML/HTMLElement.idl>

interface HTMLButtonElement : HTMLElement {

    [Reflect=formnovalidate] attribute boolean formNoValidate;
    [Reflect=formtarget] attribute DOMString formTarget;
    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString value;

};
