#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/form-elements.html#htmloptgroupelement
[Exposed=Window]
interface HTMLOptGroupElement : HTMLElement {

    [Reflect] attribute boolean disabled;
    [Reflect] attribute DOMString label;

};
