module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLOptGroupElement.h";

interface HTMLOptGroupElement : HTMLElement {

    [Reflect] attribute boolean disabled;
    [Reflect] attribute DOMString label;

};
