module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLVideoElement.h";

interface HTMLVideoElement : HTMLMediaElement {

    [Reflect] attribute DOMString poster;
    [Reflect=playsinline] attribute boolean playsInline;

};
