#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/edits.html#htmlmodelement
[Exposed=Window]
interface HTMLModElement : HTMLElement {

    [HTMLConstructor] constructor();

    [Reflect] attribute USVString cite;
    [Reflect=datetime] attribute DOMString dateTime;

};
