#import <DOM/HTMLFormControlsCollection.idl>
#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlformelement
[Exposed=Window, LegacyOverrideBuiltIns, LegacyUnenumerableNamedProperties]
interface HTMLFormElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect=accept-charset] attribute DOMString acceptCharset;
    [CEReactions] attribute USVString action;
    // FIXME: [CEReactions] attribute DOMString autocomplete;
    // FIXME: [CEReactions] attribute DOMString enctype;
    // FIXME: [CEReactions] attribute DOMString encoding;
    [CEReactions] attribute DOMString method;
    [CEReactions, Reflect] attribute DOMString name;
    [CEReactions, Reflect=novalidate] attribute boolean noValidate;
    [CEReactions, Reflect] attribute DOMString target;
    [CEReactions, Reflect] attribute DOMString rel;
    // FIXME: [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;

    [SameObject] readonly attribute HTMLFormControlsCollection elements;
    readonly attribute unsigned long length;
    getter Element (unsigned long index);
    getter (RadioNodeList or Element) (DOMString name);

    undefined submit();
    undefined requestSubmit(optional HTMLElement? submitter = null);
    [CEReactions] undefined reset();
    boolean checkValidity();
    boolean reportValidity();

};
