module Web::Bindings;

import "HTML.idl";
import "LibWeb/HTML/HTMLFrameElement.h";

interface HTMLFrameElement : HTMLElement {

    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString scrolling;
    [Reflect] attribute DOMString src;
    [Reflect=frameborder] attribute DOMString frameBorder;
    [Reflect=longdesc] attribute DOMString longDesc;

};
