#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlembedelement
[Exposed=Window]
interface HTMLEmbedElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString src;
    [CEReactions, Reflect] attribute DOMString type;
    [CEReactions, Reflect] attribute DOMString width;
    [CEReactions, Reflect] attribute DOMString height;

    [CEReactions, Reflect] attribute DOMString align;
    [CEReactions, Reflect] attribute DOMString name;

};
