#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/media.html#htmltrackelement
[Exposed=Window]
interface HTMLTrackElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute DOMString src;
    [CEReactions, Reflect] attribute DOMString srclang;
    [CEReactions, Reflect] attribute DOMString label;
    [CEReactions, Reflect] attribute boolean default;

};
