#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/semantics.html#htmlbrelement
[Exposed=Window]
interface HTMLBRElement : HTMLElement {

    [Reflect] attribute DOMString clear;

};
