#import <DOM/DocumentFragment.idl>
#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/scripting.html#htmltemplateelement
[Exposed=Window]
interface HTMLTemplateElement : HTMLElement {

    [HTMLConstructor] constructor();

    readonly attribute DocumentFragment content;

};
