#import <HTML/HTMLMediaElement.idl>

// https://html.spec.whatwg.org/#htmlaudioelement
[Exposed=Window, LegacyFactoryFunction=Audio(optional DOMString src)]
interface HTMLAudioElement : HTMLMediaElement {
    [HTMLConstructor] constructor();
};
