#import <HTML/HTMLElement.idl>

// https://html.spec.whatwg.org/multipage/text-level-semantics.html#htmltimeelement
[Exposed=Window]
interface HTMLTimeElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect=datetime] attribute DOMString dateTime;

};
