// https://html.spec.whatwg.org/multipage/canvas.html#imagedata
[Exposed=(Window,Worker), Serializable]
interface ImageData {

    readonly attribute unsigned long width;
    readonly attribute unsigned long height;
    readonly attribute Uint8ClampedArray data;

};
