module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/HTML/ImageData.h";

interface ImageData {

    readonly attribute unsigned long width;
    readonly attribute unsigned long height;
    readonly attribute Uint8ClampedArray data;

};
