interface MessagePort : EventTarget {

    undefined postMessage(any message);
    undefined start();
    undefined close();

    attribute EventHandler onmessage;
    attribute EventHandler onmessageerror;

};
