#import <HTML/Plugin.idl>

[Exposed=Window]
interface MimeType {
    readonly attribute DOMString type;
    readonly attribute DOMString description;
    readonly attribute DOMString suffixes;
    readonly attribute Plugin enabledPlugin;
};
