#import <HTML/MimeType.idl>

// https://html.spec.whatwg.org/#mimetypearray
[Exposed=Window, LegacyUnenumerableNamedProperties]
interface MimeTypeArray {
    readonly attribute unsigned long length;
    getter MimeType? item(unsigned long index);
    getter MimeType? namedItem(DOMString name);
};
