#import <HTML/NavigationType.idl>
#import <HTML/NavigationHistoryEntry.idl>

[Exposed=Window]
interface NavigationTransition {
  readonly attribute NavigationType navigationType;
  readonly attribute NavigationHistoryEntry from;
  readonly attribute Promise<undefined> finished;
};
