#import <DOM/EventHandler.idl>
#import <DOM/EventTarget.idl>

// https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigationtype
[Exposed=Window]
interface NavigationHistoryEntry : EventTarget {
    readonly attribute USVString? url;
    readonly attribute DOMString key;
    readonly attribute DOMString id;
    readonly attribute long long index;
    readonly attribute boolean sameDocument;

    any getState();

    attribute EventHandler ondispose;
};
