#import <HTML/MimeTypeArray.idl>
#import <HTML/NavigatorBeacon.idl>
#import <HTML/NavigatorID.idl>
#import <HTML/NavigatorLanguage.idl>
#import <HTML/NavigatorOnLine.idl>
#import <HTML/NavigatorConcurrentHardware.idl>
#import <HTML/PluginArray.idl>

// https://html.spec.whatwg.org/multipage/system-state.html#navigator
[Exposed=Window]
interface Navigator {
    // objects implementing this interface also implement the interfaces given below
};

// NOTE: As NavigatorContentUtils, NavigatorCookies, NavigatorPlugins, and NavigatorAutomationInformation
//       are not used in WorkerNavigator, we define them here.

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorcontentutils
interface mixin NavigatorContentUtils {
    // FIXME: [SecureContext] undefined registerProtocolHandler(DOMString scheme, USVString url);
    // FIXME: [SecureContext] undefined unregisterProtocolHandler(DOMString scheme, USVString url);
};

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorcookies
interface mixin NavigatorCookies {
    readonly attribute boolean cookieEnabled;
};

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorplugins
interface mixin NavigatorPlugins {
    [SameObject] readonly attribute PluginArray plugins;
    [SameObject] readonly attribute MimeTypeArray mimeTypes;
    boolean javaEnabled();
    readonly attribute boolean pdfViewerEnabled;
};

// https://w3c.github.io/webdriver/#dom-navigatorautomationinformation
interface mixin NavigatorAutomationInformation {
    readonly attribute boolean webdriver;
};

Navigator includes NavigatorBeacon;
Navigator includes NavigatorID;
Navigator includes NavigatorLanguage;
Navigator includes NavigatorOnLine;
Navigator includes NavigatorContentUtils;
Navigator includes NavigatorCookies;
Navigator includes NavigatorPlugins;
Navigator includes NavigatorConcurrentHardware;
Navigator includes NavigatorAutomationInformation;
