#import <HTML/NavigationType.idl>
#import <HTML/NavigationHistoryEntry.idl>

// https://html.spec.whatwg.org/#navigationtransition
[Exposed=Window]
interface NavigationTransition {
    readonly attribute NavigationType navigationType;
    readonly attribute NavigationHistoryEntry from;
    readonly attribute Promise<undefined> finished;
};
