#import <HTML/NavigatorID.idl>
#import <HTML/NavigatorLanguage.idl>
#import <HTML/NavigatorOnLine.idl>
#import <HTML/NavigatorConcurrentHardware.idl>

// https://html.spec.whatwg.org/multipage/system-state.html#navigator
[Exposed=Window]
interface Navigator {
    // objects implementing this interface also implement the interfaces given below
};

// NOTE: As NavigatorContentUtils, NavigatorCookies, and NavigatorPlugins are not used in WorkerNavigator,
//       we define them here.

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorcontentutils
interface mixin NavigatorContentUtils {
    // FIXME: [SecureContext] undefined registerProtocolHandler(DOMString scheme, USVString url);
    // FIXME: [SecureContext] undefined unregisterProtocolHandler(DOMString scheme, USVString url);
};

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorcookies
interface mixin NavigatorCookies {
    readonly attribute boolean cookieEnabled;
};

// https://html.spec.whatwg.org/multipage/system-state.html#navigatorplugins
interface mixin NavigatorPlugins {
    // FIXME: [SameObject] readonly attribute PluginArray plugins;
    // FIXME: [SameObject] readonly attribute MimeTypeArray mimeTypes;
    boolean javaEnabled();
    readonly attribute boolean pdfViewerEnabled;
};

Navigator includes NavigatorID;
Navigator includes NavigatorLanguage;
Navigator includes NavigatorOnLine;
Navigator includes NavigatorContentUtils;
Navigator includes NavigatorCookies;
Navigator includes NavigatorPlugins;
Navigator includes NavigatorConcurrentHardware;

