// https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-navigationdestination-interface
[Exposed=Window]
interface NavigationDestination {
    readonly attribute USVString url;
    readonly attribute DOMString key;
    readonly attribute DOMString id;
    readonly attribute long long index;
    readonly attribute boolean sameDocument;

    any getState();
};
