// https://html.spec.whatwg.org/multipage/system-state.html#navigatorlanguage
interface mixin NavigatorLanguage {
    readonly attribute DOMString language;
    // FIXME: readonly attribute FrozenArray<DOMString> languages;
    //        This is supposed to be a FrozenArray that always returns the same object
    readonly attribute sequence<DOMString> languages;
};
