#import <DOM/Event.idl>

interface PageTransitionEvent : Event {
    constructor(DOMString type, optional PageTransitionEventInit eventInitDict = {});

    readonly attribute boolean persisted;
};

dictionary PageTransitionEventInit : EventInit {
    boolean persisted = false;
};
