#import <HTML/MimeType.idl>

// https://html.spec.whatwg.org/#plugin
[Exposed=Window, LegacyUnenumerableNamedProperties]
interface Plugin {
    readonly attribute DOMString name;
    readonly attribute DOMString description;
    readonly attribute DOMString filename;
    readonly attribute unsigned long length;
    getter MimeType? item(unsigned long index);
    getter MimeType? namedItem(DOMString name);
};
