#import <DOM/EventTarget.idl>
#import <DOM/EventHandler.idl>
#import <HTML/ServiceWorker.idl>

// https://w3c.github.io/ServiceWorker/#serviceworkerregistration-interface
[SecureContext, Exposed=(Window,Worker)]
interface ServiceWorkerRegistration : EventTarget {
    [FIXME] readonly attribute ServiceWorker? installing;
    [FIXME] readonly attribute ServiceWorker? waiting;
    [FIXME] readonly attribute ServiceWorker? active;
    [FIXME, SameObject] readonly attribute NavigationPreloadManager navigationPreload;

    [FIXME] readonly attribute USVString scope;
    [FIXME] readonly attribute ServiceWorkerUpdateViaCache updateViaCache;

    [FIXME, NewObject] Promise<undefined> update();
    [FIXME, NewObject] Promise<boolean> unregister();

    // event
    [FIXME] attribute EventHandler onupdatefound;
};

enum ServiceWorkerUpdateViaCache {
    "imports",
    "all",
    "none"
};
