// https://html.spec.whatwg.org/#storage-2
[Exposed=Window]
interface Storage {

    readonly attribute unsigned long length;
    DOMString? key(unsigned long index);
    getter DOMString? getItem(DOMString key);
    setter undefined setItem(DOMString key, DOMString value);
    deleter undefined removeItem(DOMString key);
    undefined clear();

};
