#import <DOM/EventTarget.idl>

// https://html.spec.whatwg.org/multipage/media.html#texttrackcue
[Exposed=Window]
interface TextTrackCue : EventTarget {
    readonly attribute TextTrack? track;

    attribute DOMString id;
    attribute double startTime;
    attribute unrestricted double endTime;
    attribute boolean pauseOnExit;

    attribute EventHandler onenter;
    attribute EventHandler onexit;
};
