#import <HTML/TextTrackCue.idl>

// https://html.spec.whatwg.org/multipage/media.html#texttrackcuelist
[Exposed=Window]
interface TextTrackCueList {
    readonly attribute unsigned long length;
    getter TextTrackCue (unsigned long index);
    TextTrackCue? getCueById(DOMString id);
};
