// https://html.spec.whatwg.org/multipage/media.html#timeranges
[Exposed=Window]
interface TimeRanges {
    readonly attribute unsigned long length;
    double start(unsigned long index);
    double end(unsigned long index);
};
