#import <DOM/Event.idl>
#import <HTML/AudioTrack.idl>
#import <HTML/TextTrack.idl>
#import <HTML/VideoTrack.idl>

// https://html.spec.whatwg.org/multipage/media.html#trackevent
[Exposed=Window]
interface TrackEvent : Event {
    constructor(DOMString type, optional TrackEventInit eventInitDict = {});

    readonly attribute (VideoTrack or AudioTrack or TextTrack)? track;
};

dictionary TrackEventInit : EventInit {
    (VideoTrack or AudioTrack or TextTrack)? track = null;
};
