#import <DOM/Event.idl>
#import <HTML/AudioTrack.idl>
#import <HTML/VideoTrack.idl>

// https://html.spec.whatwg.org/multipage/media.html#trackevent
[Exposed=Window]
interface TrackEvent : Event {
    constructor(DOMString type, optional TrackEventInit eventInitDict = {});

    // FIXME: Should be: (VideoTrack or AudioTrack or TextTrack)?
    readonly attribute (VideoTrack or AudioTrack)? track;
};

dictionary TrackEventInit : EventInit {
    // FIXME: Should be: (VideoTrack or AudioTrack or TextTrack)?
    (VideoTrack or AudioTrack)? track = null;
};
