#import <DOM/EventHandler.idl>
#import <DOM/EventTarget.idl>

// https://html.spec.whatwg.org/multipage/nav-history-apis.html#window
[Global=Window, Exposed=Window, LegacyUnenumerableNamedProperties, UseNewAKString]
interface Window : EventTarget {
    // user prompts
    undefined alert();
    undefined alert(DOMString message);
    boolean confirm(optional DOMString message = "");
    DOMString? prompt(optional DOMString message = "", optional DOMString default = "");

    undefined postMessage(any message, USVString targetOrigin);
    // FIXME: undefined postMessage(any message, USVString targetOrigin, optional sequence<object> transfer = []);
    // FIXME: undefined postMessage(any message, optional WindowPostMessageOptions options = {});
};
Window includes GlobalEventHandlers;
Window includes WindowEventHandlers;
