// https://html.spec.whatwg.org/#workerlocation
[Exposed=Worker]
interface WorkerLocation {
    stringifier readonly attribute USVString href;
    readonly attribute USVString origin;
    readonly attribute USVString protocol;
    readonly attribute USVString host;
    readonly attribute USVString hostname;
    readonly attribute USVString port;
    readonly attribute USVString pathname;
    readonly attribute USVString search;
    readonly attribute USVString hash;
};
