#import <DOM/EventHandler.idl>
#import <MediaSourceExtensions/SourceBuffer.idl>

// https://w3c.github.io/media-source/#managedsourcebuffer-interface
[Exposed=(Window,DedicatedWorker)]
interface ManagedSourceBuffer : SourceBuffer {
    [FIXME] attribute EventHandler onbufferedchange;
};
