include ../../Makefile.common

OBJS = \
    ProcessModel.o \
    ProcessTableView.o \
    MemoryStatsWidget.o \
    GraphWidget.o \
    ProcessStacksWidget.o \
    ProcessMemoryMapWidget.o \
    ProcessMemoryMapModel.o \
    main.o

APP = ProcessManager

include ../Makefile.common
