--- dos2unix-7.2.4/Makefile.orig	2021-12-06 22:52:37.468010400 -0700
+++ dos2unix-7.2.4/Makefile	2021-12-06 22:53:25.508010400 -0700
@@ -316,6 +316,8 @@
         EXTRA_DEFS += -Dhpux -D_HPUX_SOURCE
 endif
 
+LIBS_EXTRA = -lintl 
+
 
 # ............................................................ flags ...
 
