OBJS = \
    VBForm.o \
    VBWidget.o \
    VBWidgetRegistry.o \
    VBWidgetPropertyModel.o \
    VBProperty.o \
    VBPropertiesWindow.o \
    main.o

PROGRAM = VisualBuilder

LIB_DEPS = GUI Gfx IPC Core

include ../../Makefile.common
