# Set update schedule for GitHub Actions
version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "CI:"
    groups:
      actions:
        group-by: dependency-name
