OBJS = \
    ProcessModel.o \
    DevicesModel.o \
    ProcessTableView.o \
    MemoryStatsWidget.o \
    GraphWidget.o \
    ProcessStacksWidget.o \
    ProcessMemoryMapWidget.o \
    ProcessFileDescriptorMapWidget.o \
    NetworkStatisticsWidget.o \
    main.o

PROGRAM = SystemMonitor

LDFLAGS = -lgui -ldraw -lprotocol -lpcidb -lipc -lthread -lpthread -lcore -lc

include ../../Makefile.common
