include ../../Makefile.common

OBJS = \
    ProcessModel.o \
    ProcessTableView.o \
    MemoryStatsWidget.o \
    GraphWidget.o \
    ProcessStacksWidget.o \
    ProcessMemoryMapWidget.o \
    ProcessFileDescriptorMapWidget.o \
    NetworkStatisticsWidget.o \
    main.o

APP = SystemMonitor

include ../Makefile.common
