# Pipeline definition for nightly or other scheduled jobs we don't want to run on every PR in Azure
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
  - stage: Toolchain
    dependsOn: []
    jobs:
      - template: Meta/Azure/Toolchain.yml

  - stage: SerenityOS (Coverage)
    dependsOn: Toolchain
    jobs:
      - template: Meta/Azure/Serenity.yml
        parameters:
          arch: 'x86_64'
          coverage: 'ON'
