PYTHON_VERSION="3.9.2"
PYTHON_ARCHIVE="Python-${PYTHON_VERSION}.tar.xz"
PYTHON_ARCHIVE_URL="https://www.python.org/ftp/python/${PYTHON_VERSION}/${PYTHON_ARCHIVE}"
PYTHON_ARCHIVE_MD5SUM="f0dc9000312abeb16de4eccce9a870ab"
