trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage: FilterPR
    dependsOn: []
    condition: eq(variables['Build.Reason'], 'PullRequest')

    jobs:
      - template: Meta/Azure/FilterPR.yml

  - stage: Lagom
    dependsOn: FilterPR
    condition: in(dependencies.FilterPR.result, 'Succeeded', 'Skipped')

    jobs:
      - template: Meta/Azure/Lagom.yml
        parameters:
          os: 'Linux'
          lagom_lints: true

      - template: Meta/Azure/Lagom.yml
        parameters:
          os: 'Linux'
          fuzzer: 'Fuzz'

      - template: Meta/Azure/Lagom.yml
        parameters:
          os: 'macOS'

  - stage: SerenityOS
    dependsOn: FilterPR
    condition: in(dependencies.FilterPR.result, 'Succeeded', 'Skipped')

    jobs:
      - template: Meta/Azure/Serenity.yml
        parameters:
          arch: 'x86_64'
