trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage: Lagom
    dependsOn: []

    jobs:
      - template: Meta/Azure/Lagom.yml
        parameters:
          os: 'Linux'
          lagom_lints: true
