subdirs: $(SUBDIRS)
$(SUBDIRS):
	@flock $@ $(MAKE) $(PARALLEL_BUILD) -C $@

all: $(subdirs)

SUBDIRS_CLEAN = $(addsuffix .clean,$(SUBDIRS))
clean: $(SUBDIRS_CLEAN)
$(SUBDIRS_CLEAN): %.clean:
	@flock $* $(MAKE) $(PARALLEL_BUILD) -C $* clean

SUBDIRS_INSTALL = $(addsuffix .install,$(SUBDIRS))
install: $(SUBDIRS_INSTALL)
$(SUBDIRS_INSTALL): %.install:
	@flock $* $(MAKE) $(PARALLEL_BUILD) -C $* install

.PHONY: all clean install $(SUBDIRS)
