#!/usr/bin/env -S bash ../.port_include.sh
port='freeciv'
version='3.1.1'
useconfigure='true'
use_fresh_config_sub='true'
config_sub_paths=(
    'bootstrap/config.sub'
)
configopts=(
    '--enable-client=sdl2'
    '--enable-fcmp=no'
    '--enable-fcdb=no'
)
files=(
    "http://files.freeciv.org/stable/freeciv-${version}.tar.xz#b2bd00c0e2a6c81bcb52aa0dddf81f2f4543705bf7a9fcd5afac3f7b3fff5ef6"
)
depends=(
    'curl'
    'gettext'
    'libicu'
    'SDL2'
    'SDL2_gfx'
    'SDL2_image'
    'SDL2_mixer'
    'SDL2_ttf'
    'zstd'
    'xz'
)
launcher_name='Freeciv'
launcher_category='&Games'
launcher_command='/usr/local/bin/freeciv-sdl2'
icon_file='windows/client.ico'
