OBJS = \
    Project.o \
    ProjectFile.o \
    TerminalWrapper.o \
    FindInFilesWidget.o \
    ProcessStateWidget.o \
    FormEditorWidget.o \
    FormWidget.o \
    CppLexer.o \
    Editor.o \
    EditorWrapper.o \
    Locator.o \
    Tool.o \
    CursorTool.o \
    WidgetTool.o \
    WidgetTreeModel.o \
    main.o

PROGRAM = HackStudio

LDFLAGS = -lvt -lhtml -lprotocol -lipc -lmarkdown -lgui -ldraw -lthread -lpthread -lcore -lc

include ../../Makefile.common
