OBJS = \
    Project.o \
    ProjectFile.o \
    TerminalWrapper.o \
    FindInFilesWidget.o \
    ProcessStateWidget.o \
    FormEditorWidget.o \
    FormWidget.o \
    Editor.o \
    EditorWrapper.o \
    Locator.o \
    Tool.o \
    CursorTool.o \
    WidgetTool.o \
    WidgetTreeModel.o \
    main.o

PROGRAM = HackStudio

LIB_DEPS = GUI Web VT Protocol Markdown Gfx IPC Thread Pthread Core

include ../../Makefile.common
