OBJS = \
    RemoteObjectGraphModel.o \
    RemoteObjectPropertyModel.o \
    RemoteProcess.o \
    RemoteObject.o \
    main.o

PROGRAM = Inspector

LDFLAGS = -lgui -ldraw -lipc -lcore -lc

include ../../Makefile.common
