OBJS = \
    RemoteObjectGraphModel.o \
    RemoteObjectPropertyModel.o \
    RemoteProcess.o \
    RemoteObject.o \
    main.o

PROGRAM = Inspector

LIB_DEPS = GUI Draw IPC Core

LDFLAGS = -static

include ../../Makefile.common
