USE_HOST_CXX = 1

PROGRAM = Generate_CSS_PropertyID_h

OBJS = \
    Generate_CSS_PropertyID_h.o \
    ../../../../AK/StringUtils.o \
    ../../../../AK/String.o \
    ../../../../AK/StringImpl.o \
    ../../../../AK/StringBuilder.o \
    ../../../../AK/StringView.o \
    ../../../../AK/JsonValue.o \
    ../../../../AK/JsonParser.o \
    ../../../../AK/LogStream.o \
    ../../../../Libraries/LibCore/IODevice.o \
    ../../../../Libraries/LibCore/File.o \
    ../../../../Libraries/LibCore/Object.o \
    ../../../../Libraries/LibCore/Event.o \
    ../../../../Libraries/LibCore/Socket.o \
    ../../../../Libraries/LibCore/LocalSocket.o \
    ../../../../Libraries/LibCore/Notifier.o \
    ../../../../Libraries/LibCore/LocalServer.o \
    ../../../../Libraries/LibCore/EventLoop.o

include ../../../../Makefile.common
