#!/usr/bin/env -S bash ../.port_include.sh
port='mc'
version='4.8.30'
useconfigure='true'
files=(
    "http://ftp.midnight-commander.org/mc-${version}.tar.xz#5ebc3cb2144b970c5149fda556c4ad50b78780494696cdf2d14a53204c95c7df"
)
depends=(
    'gettext'
    'glib'
    'ncurses'
    'vim'
)
configopts=(
    "--with-sysroot=${SERENITY_INSTALL_ROOT}"
    '--disable-largefile'
    '--disable-vfs'
    '--without-edit'
    '--without-x'
    '--with-homedir'
    '--with-screen=ncurses'
)
use_fresh_config_sub='true'
config_sub_paths=(
    'config/config.sub'
)
