#!/usr/bin/env -S bash ../.port_include.sh
port='mc'
version='4.8.31'
useconfigure='true'
files=(
    "http://ftp.midnight-commander.org/mc-${version}.tar.xz#24191cf8667675b8e31fc4a9d18a0a65bdc0598c2c5c4ea092494cd13ab4ab1a"
)
depends=(
    'gettext'
    'glib'
    'ncurses'
    'vim'
)
configopts=(
    "--with-sysroot=${SERENITY_INSTALL_ROOT}"
    '--disable-largefile'
    '--disable-vfs'
    '--without-edit'
    '--without-x'
    '--with-homedir'
    '--with-screen=ncurses'
)
use_fresh_config_sub='true'
config_sub_paths=(
    'config/config.sub'
)
