timeout: 3
wallpaper: boot():/wallpaper.png

/SerenityOS (normal)
    protocol: multiboot1
    cmdline: root=block100:2
    path: boot():/Kernel

/SerenityOS (text mode)
    protocol: multiboot1
    cmdline: graphics_subsystem_mode=off root=block100:2
    path: boot():/Kernel

/SerenityOS (no ACPI)
    protocol: multiboot1
    cmdline: root=block100:2 acpi=off
    path: boot():/Kernel

/SerenityOS (with serial output)
    protocol: multiboot1
    cmdline: root=block100:2 serial_debug
    path: boot():/Kernel
