install:
	mkdir -p $(SERENITY_BASE_DIR)/Root/usr/include/LibBareMetal/
	mkdir -p $(SERENITY_BASE_DIR)/Root/usr/include/LibBareMetal/Output/
	cp ../LibBareMetal/*.h $(SERENITY_BASE_DIR)/Root/usr/include/LibBareMetal/
	cp ../LibBareMetal/Output/*.h $(SERENITY_BASE_DIR)/Root/usr/include/LibBareMetal/Output/

include ../../Makefile.common
