#import <FileAPI/Blob.idl>
#import <URL/URLSearchParams.idl>

// https://fetch.spec.whatwg.org/#typedefdef-xmlhttprequestbodyinit
typedef (Blob or BufferSource or URLSearchParams or USVString) XMLHttpRequestBodyInit;
