#import <SVG/SVGLength.idl>

// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedLength
[Exposed=Window]
interface SVGAnimatedLength {
    readonly attribute SVGLength baseVal;
    readonly attribute SVGLength animVal;
};
