// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedString
[Exposed=Window]
interface SVGAnimatedString {
    attribute DOMString baseVal;
    [ImplementedAs=base_val] readonly attribute DOMString animVal;
};
