#import <SVG/SVGGeometryElement.idl>

[Exposed=Window]
interface SVGCircleElement : SVGGeometryElement {
    // [SameObject] readonly attribute SVGAnimatedLength cx;
    // [SameObject] readonly attribute SVGAnimatedLength cy;
    // [SameObject] readonly attribute SVGAnimatedLength r;
};
