#import <SVG/SVGElement.idl>

// https://drafts.fxtf.org/css-masking/#InterfaceSVGClipPathElement
[Exposed=Window]
interface SVGClipPathElement : SVGElement {

    [FIXME] readonly attribute SVGAnimatedEnumeration clipPathUnits;
    [FIXME] readonly attribute SVGAnimatedTransformList transform;

};
