#import <DOM/Element.idl>
#import <HTML/HTMLElement.idl>
#import <HTML/DOMStringMap.idl>

// https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement
[Exposed=Window]
interface SVGElement : Element {
};

SVGElement includes HTMLOrSVGElement;
