#import <SVG/SVGAnimatedLength.idl>
#import <SVG/SVGGeometryElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#shapes-InterfaceSVGEllipseElement
[Exposed=Window]
interface SVGEllipseElement : SVGGeometryElement {
    [SameObject] readonly attribute SVGAnimatedLength cx;
    [SameObject] readonly attribute SVGAnimatedLength cy;
    [SameObject] readonly attribute SVGAnimatedLength rx;
    [SameObject] readonly attribute SVGAnimatedLength ry;
};
