#import <SVG/SVGAnimatedLength.idl>
#import <SVG/SVGGraphicsElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#embedded-InterfaceSVGForeignObjectElement
[Exposed=Window]
interface SVGForeignObjectElement : SVGGraphicsElement {

    [SameObject] readonly attribute SVGAnimatedLength x;
    [SameObject] readonly attribute SVGAnimatedLength y;
    [SameObject] readonly attribute SVGAnimatedLength width;
    [SameObject] readonly attribute SVGAnimatedLength height;

};
