#import <SVG/SVGElement.idl>
#import <SVG/SVGURIReference.idl>

// https://svgwg.org/svg2-draft/single-page.html#pservers-InterfaceSVGGradientElement
[Exposed=Window]
interface SVGGradientElement : SVGElement {

    // Spread Method Types
    const unsigned short SVG_SPREADMETHOD_UNKNOWN = 0;
    const unsigned short SVG_SPREADMETHOD_PAD = 1;
    const unsigned short SVG_SPREADMETHOD_REFLECT = 2;
    const unsigned short SVG_SPREADMETHOD_REPEAT = 3;

    [FIXME, SameObject] readonly attribute SVGAnimatedEnumeration gradientUnits;
    [FIXME, SameObject] readonly attribute SVGAnimatedTransformList gradientTransform;
    [FIXME, SameObject] readonly attribute SVGAnimatedEnumeration spreadMethod;

};

SVGGradientElement includes SVGURIReference;
