#import <SVG/SVGGraphicsElement.idl>
#import <SVG/SVGURIReference.idl>

// https://svgwg.org/svg2-draft/embedded.html#InterfaceSVGImageElement
[Exposed=Window]
interface SVGImageElement : SVGGraphicsElement {
    [SameObject] readonly attribute SVGAnimatedLength x;
    [SameObject] readonly attribute SVGAnimatedLength y;
    [SameObject] readonly attribute SVGAnimatedLength width;
    [SameObject] readonly attribute SVGAnimatedLength height;
    [FIXME, SameObject] readonly attribute SVGAnimatedPreserveAspectRatio preserveAspectRatio;
    [Reflect=crossorigin, Enumerated=CORSSettingsAttribute] attribute DOMString? crossOrigin;
};

SVGImageElement includes SVGURIReference;
