#import <SVG/SVGAnimatedLength.idl>
#import <SVG/SVGGeometryElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#shapes-InterfaceSVGLineElement
[Exposed=Window]
interface SVGLineElement : SVGGeometryElement {
    [SameObject] readonly attribute SVGAnimatedLength x1;
    [SameObject] readonly attribute SVGAnimatedLength y1;
    [SameObject] readonly attribute SVGAnimatedLength x2;
    [SameObject] readonly attribute SVGAnimatedLength y2;
};
