#import <SVG/SVGGeometryElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#shapes-InterfaceSVGPolylineElement
[Exposed=Window]
interface SVGPolylineElement : SVGGeometryElement {
};

// SVGPolylineElement includes SVGAnimatedPoints;
