#import <SVG/SVGAnimatedLength.idl>
#import <SVG/SVGGradientElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#pservers-InterfaceSVGRadialGradientElement
[Exposed=Window]
interface SVGRadialGradientElement : SVGGradientElement {
    [SameObject] readonly attribute SVGAnimatedLength cx;
    [SameObject] readonly attribute SVGAnimatedLength cy;
    [SameObject] readonly attribute SVGAnimatedLength r;
    [SameObject] readonly attribute SVGAnimatedLength fx;
    [SameObject] readonly attribute SVGAnimatedLength fy;
    [SameObject] readonly attribute SVGAnimatedLength fr;
};
