#import <SVG/SVGGraphicsElement.idl>

// https://svgwg.org/svg2-draft/struct.html#InterfaceSVGSymbolElement
[Exposed=Window]
interface SVGSymbolElement : SVGGraphicsElement {

};

SVGSymbolElement includes SVGFitToViewBox;
