#import <CSS/LinkStyle.idl>
#import <SVG/SVGElement.idl>

// https://svgwg.org/svg2-draft/single-page.html#styling-InterfaceSVGStyleElement
[Exposed=Window]
interface SVGStyleElement : SVGElement {
    [Reflect] attribute DOMString type;
    [Reflect] attribute DOMString media;
    [Reflect] attribute DOMString title;
};

SVGStyleElement includes LinkStyle;
