#import <CSS/LinkStyle.idl>
#import <SVG/SVGElement.idl>

[Exposed=Window, UseDeprecatedAKString]
interface SVGStyleElement : SVGElement {
  [Reflect] attribute DOMString type;
  [Reflect] attribute DOMString media;
  [Reflect] attribute DOMString title;
};

SVGStyleElement includes LinkStyle;
