#import <Streams/QueuingStrategyInit.idl>

// https://streams.spec.whatwg.org/#blqs-class-definition
[Exposed=*]
interface ByteLengthQueuingStrategy {
    constructor(QueuingStrategyInit init);

    readonly attribute unrestricted double highWaterMark;

    // FIXME: readonly attribute Function size;
};
