#import <Streams/QueuingStrategyInit.idl>

// https://streams.spec.whatwg.org/#cqs-class-definition
[Exposed=*]
interface CountQueuingStrategy {
    constructor(QueuingStrategyInit init);

    readonly attribute unrestricted double highWaterMark;

    // FIXME: readonly attribute Function size;
};
