callback QueuingStrategySize = unrestricted double (any chunk);

// https://streams.spec.whatwg.org/#dictdef-queuingstrategy
dictionary QueuingStrategy {
    unrestricted double highWaterMark;
    QueuingStrategySize size;
};
