// Dummy definition so we can use ReadableStream as a type in Fetch.

// https://streams.spec.whatwg.org/#readablestream
[Exposed=*, Transferable]
interface ReadableStream {
    // FIXME: optional QueuingStrategy strategy = {}
    constructor(optional object underlyingSource);
};
