#import <Streams/QueuingStrategy.idl>
#import <Streams/ReadableStreamBYOBReader.idl>
#import <Streams/ReadableStreamDefaultReader.idl>

// https://streams.spec.whatwg.org/#readablestream
[Exposed=*, Transferable]
interface ReadableStream {
    constructor(optional object underlyingSource, optional QueuingStrategy strategy = {});

    readonly attribute boolean locked;

    Promise<undefined> cancel(optional any reason);
    // FIXME: optional ReadableStreamGetReaderOptions options = {}
    ReadableStreamReader getReader();
};

typedef (ReadableStreamDefaultReader or ReadableStreamBYOBReader) ReadableStreamReader;
