#import <Streams/ReadableStream.idl>
#import <Streams/ReadableStreamGenericReader.idl>

// https://streams.spec.whatwg.org/#readablestreambyobreader
[Exposed=*]
interface ReadableStreamBYOBReader {
    constructor(ReadableStream stream);

    // FIXME: Implement
    // Promise<ReadableStreamReadResult> read(ArrayBufferView view);
    undefined releaseLock();
};
ReadableStreamBYOBReader includes ReadableStreamGenericReader;
