// https://streams.spec.whatwg.org/#transformstreamdefaultcontroller
[Exposed=*]
interface TransformStreamDefaultController {
    readonly attribute unrestricted double? desiredSize;

    // FIXME: undefined enqueue(optional any chunk);
    undefined error(optional any reason);
    // FIXME: undefined terminate();
};
