[Exposed=*, Transferable]
interface WritableStream {
    // FIXME: optional QueuingStrategy strategy = {}
    constructor(optional object underlyingSink);

    readonly attribute boolean locked;

    // FIXME:
    // Promise<undefined> abort(optional any reason);
    // WritableStreamDefaultWriter getWriter();

    Promise<undefined> close();
};
