#import <DOM/AbortSignal.idl>

// https://streams.spec.whatwg.org/#writablestreamdefaultcontroller
[Exposed=*]
interface WritableStreamDefaultController {
    readonly attribute AbortSignal signal;
    undefined error(optional any e);
};
