#import <Streams/QueuingStrategy.idl>
#import <Streams/WritableStreamDefaultWriter.idl>

// https://streams.spec.whatwg.org/#writablestream
[Exposed=*, Transferable]
interface WritableStream {
    constructor(optional object underlyingSink, optional QueuingStrategy strategy = {});

    readonly attribute boolean locked;

    Promise<undefined> abort(optional any reason);
    Promise<undefined> close();
    WritableStreamDefaultWriter getWriter();
};
