# Copyright (c) 2012, 2016, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.

CFLAGS =	-fPIC -O
OBJS =		myfile.o
HEADERS =	MyCanvas.h
CLASSES =	MyCanvas.class

ENV =		/usr/bin/env
JAVA =		$(TESTJAVA)/bin/java -classpath .
JAVAC =		$(TESTJAVA)/bin/javac
LINK =		ld

J_INC =		$(TESTJAVA)/include
INCLUDES =	-I$(J_INC) -I$(J_INC)/$(SYST) -I.
LIBS =		-L$(TESTJAVA)/lib -ljawt -lX11

all:		$(CLASSES) libmylib.so

libmylib.so: $(HEADERS) $(OBJS) 
	$(LINK) -G -o libmylib.so $(OBJS) $(LIBS)

myfile.o:	$(TESTSRC)/myfile.c
	$(CC)  $(CFLAGS) $(INCLUDES) -c $(TESTSRC)/myfile.c

clean:
	rm -rf libmylib.so $(HEADERS) $(CLASSES) $(OBJS)
