# Copyright (c) 2012, 2013, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.

CFLAGS =	-nologo
OBJS =		myfile.obj
HEADERS =	MyCanvas.h
CLASSES =	MyCanvas.class

DEL =		del /Q
LINK =		link

INCLUDES =	-I$(TESTJAVA)\include\win32 -I$(TESTJAVA)\include

LIBS =		gdi32.lib user32.lib $(TESTJAVA)\lib\jawt.lib

all:		$(CLASSES) mylib.dll

mylib.dll: $(HEADERS) $(OBJS) 
	$(LINK) -nologo -dll -out:mylib.dll $(OBJS) $(LIBS)

myfile.obj: $(TESTSRC)\myfile.cpp
	$(CC) $(CFLAGS) $(INCLUDES) -c $(TESTSRC)\myfile.cpp

clean:
	$(DEL) mylib.* 
	$(DEL) $(HEADERS) $(CLASSES)
	$(DEL) *.obj
