#import <HighResolutionTime/Performance.idl>

// https://w3c.github.io/performance-timeline/#performanceobserverentrylist-interface
[Exposed=(Window,Worker)]
interface PerformanceObserverEntryList {
    PerformanceEntryList getEntries();
    PerformanceEntryList getEntriesByType(DOMString type);
    PerformanceEntryList getEntriesByName(DOMString name, optional DOMString type);
};
