#import <HighResolutionTime/DOMHighResTimeStamp.idl>

// https://www.w3.org/TR/performance-timeline/#dom-performanceentry
[Exposed=(Window,Worker)]
interface PerformanceEntry {
    readonly attribute DOMString name;
    readonly attribute DOMString entryType;
    readonly attribute DOMHighResTimeStamp startTime;
    readonly attribute DOMHighResTimeStamp duration;
    [Default] object toJSON();
};
