#!/bin/sh

if [ "$1" = "b" ]; then
    # ./run b: bochs
    bochs -q -f .bochsrc
elif [ "$1" = "qn" ]; then
    # ./run qn: qemu without network
    qemu-system-i386 -s -m 32 -device e1000 -drive format=raw,file=.floppy-image,if=floppy -drive format=raw,file=_fs_contents #$@
else
    echo run with net
    # ./run: qemu with network
    sudo qemu-system-i386 -s -m 32 -netdev tap,id=br0 -device e1000,netdev=br0 -drive format=raw,file=.floppy-image,if=floppy -drive format=raw,file=_fs_contents #$
fi

