#import <DOM/NamedNodeMap.idl>

[Exposed=Nobody] interface Inspector {

    undefined inspectorLoaded();
    undefined inspectDOMNode(long nodeID, optional long pseudoElement);

    undefined setDOMNodeText(long nodeID, DOMString text);
    undefined setDOMNodeTag(long nodeID, DOMString tag);
    undefined addDOMNodeAttributes(long nodeID, NamedNodeMap attributes);
    undefined replaceDOMNodeAttribute(long nodeID, unsigned long long attributeIndex, NamedNodeMap replacementAttributes);

    undefined requestDOMTreeContextMenu(long nodeID, long clientX, long clientY, DOMString type, DOMString? tag, unsigned long long? attributeIndex);

    undefined requestStyleSheetSource(DOMString type, long? domNodeID, DOMString? url);

    undefined executeConsoleScript(DOMString script);

    undefined exportInspectorHTML(DOMString html);

};
