#import <Geometry/DOMPointReadOnly.idl>

// https://drafts.fxtf.org/geometry/#dompoint
[Exposed=(Window,Worker), Serializable, LegacyWindowAlias=SVGPoint]
interface DOMPoint : DOMPointReadOnly {

    constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
                optional unrestricted double z = 0, optional unrestricted double w = 1);

    [NewObject] static DOMPoint fromPoint(optional DOMPointInit other = {});

    inherit attribute unrestricted double x;
    inherit attribute unrestricted double y;
    inherit attribute unrestricted double z;
    inherit attribute unrestricted double w;

};
