// https://drafts.fxtf.org/geometry/#dompointreadonly
interface DOMPointReadOnly {

    constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
                optional unrestricted double z = 0, optional unrestricted double w = 1);

    // FIXME: [NewObject] static DOMPointReadOnly fromPoint(optional DOMPointInit other = {});

    readonly attribute unrestricted double x;
    readonly attribute unrestricted double y;
    readonly attribute unrestricted double z;
    readonly attribute unrestricted double w;

    // FIXME: DOMPoint matrixTransform(optional DOMMatrixInit matrix = {});

    // FIXME: [Default] object toJSON();
};
