interface DOMRectReadOnly {

    constructor(optional double x = 0, optional double y = 0, optional double width = 0, optional double height = 0);

    readonly attribute double x;
    readonly attribute double y;
    readonly attribute double width;
    readonly attribute double height;

    readonly attribute double top;
    readonly attribute double right;
    readonly attribute double bottom;
    readonly attribute double left;

};
