OBJS = \
    PlaybackManager.o \
    SampleWidget.o \
    SoundPlayerWidget.o \
    main.o

PROGRAM = SoundPlayer

LIB_DEPS = GUI Draw Audio IPC Thread Pthread Core

LDFLAGS = -static

include ../../Makefile.common
