OBJS = \
    PlaybackManager.o \
    SampleWidget.o \
    SoundPlayerWidget.o \
    main.o

PROGRAM = SoundPlayer

LDFLAGS = -lgui -ldraw -laudio -lipc -lthread -lpthread -lcore -lc

include ../../Makefile.common
