#!/usr/bin/env -S bash ../.port_include.sh
port='freetype'
version='2.13.2'
files=(
    "https://download.savannah.gnu.org/releases/freetype/freetype-${version}.tar.gz#1ac27e16c134a7f2ccea177faba19801131116fd682efc1f5737037c5db224b5"
)
useconfigure='true'
use_fresh_config_sub='true'
config_sub_paths=(
    'builds/unix/config.sub'
)
configopts=(
    "--with-sysroot=${SERENITY_INSTALL_ROOT}"
    '--with-brotli=no'
    '--with-bzip2=no'
    '--with-zlib=no'
    '--with-harfbuzz=no'
    '--with-png=no'
)
