interface HTMLIFrameElement : HTMLElement {

    [Reflect] attribute DOMString src;
    [Reflect] attribute DOMString srcdoc;
    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString allow;
    [Reflect] attribute DOMString width;
    [Reflect] attribute DOMString height;
    [Reflect=allowfullscreen] attribute boolean allowFullscreen;

    [ReturnNullIfCrossOrigin] readonly attribute Document? contentDocument;
}
