interface HTMLAnchorElement : HTMLElement {

    [Reflect] attribute DOMString target;
    [Reflect] attribute DOMString download;
    [Reflect] attribute DOMString ping;
    [Reflect] attribute DOMString rel;
    [Reflect] attribute DOMString hreflang;
    [Reflect] attribute DOMString type;

    [Reflect] attribute DOMString coords;
    [Reflect] attribute DOMString charset;
    [Reflect] attribute DOMString name;
    [Reflect] attribute DOMString rev;
    [Reflect] attribute DOMString shape;

}
