#import <CSS/CSSGroupingRule.idl>

// https://drafts.csswg.org/css-conditional-3/#the-cssconditionrule-interface
[Exposed=Window]
interface CSSConditionRule : CSSGroupingRule {
    readonly attribute CSSOMString conditionText;
};
