#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleDeclaration.idl>

// https://drafts.csswg.org/css-fonts/#om-fontface
[Exposed=Window]
interface CSSFontFaceRule : CSSRule {
    readonly attribute CSSStyleDeclaration style;
};
