#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleSheet.idl>
#import <CSS/MediaList.idl>

// https://drafts.csswg.org/cssom/#the-cssimportrule-interface
[Exposed=Window]
interface CSSImportRule : CSSRule {
    readonly attribute USVString href;
    // FIXME: [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
    [SameObject, ImplementedAs=style_sheet_for_bindings] readonly attribute CSSStyleSheet styleSheet;
    [FIXME] readonly attribute CSSOMString? layerName;
    [FIXME] readonly attribute CSSOMString? supportsText;
};
