#import <CSS/CSSRule.idl>

[Exposed=Window, UseNewAKString]
interface CSSKeyframeRule : CSSRule {
    attribute CSSOMString keyText;
    [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
