#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleDeclaration.idl>

// https://drafts.csswg.org/css-animations-1/#interface-csskeyframerule-idl
[Exposed=Window]
interface CSSKeyframeRule : CSSRule {
    attribute CSSOMString keyText;
    [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
