#import <CSS/CSSConditionRule.idl>
#import <CSS/MediaList.idl>

[Exposed=Window, NoInstanceWrapper]
interface CSSMediaRule : CSSConditionRule {
    [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
};
