#import <CSS/CSSConditionRule.idl>
#import <CSS/MediaList.idl>

// https://drafts.csswg.org/css-conditional-3/#the-cssmediarule-interface
[Exposed=Window]
interface CSSMediaRule : CSSConditionRule {
    [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
};
