#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleDeclaration.idl>

// https://drafts.csswg.org/css-nesting-1/#cssnesteddeclarations
[Exposed=Window]
interface CSSNestedDeclarations : CSSRule {
    // FIXME: Should be a CSSStyleProperties, once we have that
    [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
