#import <CSS/CSSRule.idl>

// https://www.w3.org/TR/cssom/#the-cssnamespacerule-interface
[Exposed=Window]
interface CSSNamespaceRule : CSSRule {
    readonly attribute CSSOMString namespaceURI;
    readonly attribute CSSOMString prefix;
};
