#import <CSS/CSSRule.idl>

// https://www.w3.org/TR/cssom/#the-cssrulelist-interface
[Exposed=Window]
interface CSSRuleList {

    getter CSSRule? item(unsigned long index);
    readonly attribute unsigned long length;

};
