[CustomGet,CustomSet,CustomHasProperty]
interface CSSStyleDeclaration {

    readonly attribute unsigned long length;
    CSSOMString item(unsigned long index);

    CSSOMString getPropertyValue(CSSOMString property);

    [CEReactions] undefined setProperty(CSSOMString property, [LegacyNullToEmptyString] CSSOMString value);

};
