interface CSSStyleSheet : StyleSheet {
    // readonly attribute CSSRule? ownerRule;
    [SameObject] readonly attribute CSSRuleList cssRules;
    unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0);
    undefined deleteRule(unsigned long index);
    undefined removeRule(unsigned long index);
};
