#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleDeclaration.idl>

interface CSSStyleRule : CSSRule {

    attribute CSSOMString selectorText;
    [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;

};
