#import <Animations/Animation.idl>

// https://drafts.csswg.org/css-transitions-2/#the-CSSTransition-interface
[Exposed=Window]
interface CSSTransition : Animation {
    readonly attribute CSSOMString transitionProperty;
};
