#import <CSS/CSSStyleSheet.idl>

// https://drafts.csswg.org/cssom/#the-stylesheetlist-interface
[Exposed=Window]
interface StyleSheetList {
    getter CSSStyleSheet? item(unsigned long index);
    readonly attribute unsigned long length;
};
