#import <DOM/EventTarget.idl>

// https://drafts.csswg.org/cssom-view/#the-visualviewport-interface
[Exposed=Window]
interface VisualViewport : EventTarget {

    readonly attribute double offsetLeft;
    readonly attribute double offsetTop;

    readonly attribute double pageLeft;
    readonly attribute double pageTop;

    readonly attribute double width;
    readonly attribute double height;

    readonly attribute double scale;

    attribute EventHandler onresize;
    attribute EventHandler onscroll;
    attribute EventHandler onscrollend;

};
