include ../../Makefile.common

OBJS = \
    IRCClient.o \
    IRCChannel.o \
    IRCQuery.o \
    IRCLogBuffer.o \
    IRCAppWindow.o \
    IRCWindow.o \
    IRCWindowListModel.o \
    IRCChannelMemberListModel.o \
    main.o

APP = IRCClient

include ../Makefile.common
