#import <WebAudio/AudioNode.idl>

// https://webaudio.github.io/web-audio-api/#AudioDestinationNode
[Exposed=Window]
interface AudioDestinationNode : AudioNode {
    readonly attribute unsigned long maxChannelCount;
};
