OBJS = \
    Service.o \
    main.o

PROGRAM = SystemServer

LDFLAGS = -lcore -lc

install:
	mkdir -p ../../Root/usr/include/SystemServer/
	cp *.h ../../Root/usr/include/SystemServer/

include ../../Makefile.common
