#import <DOM/AbortSignal.idl>

[Exposed=(Window,Worker)]
interface AbortController {
    constructor();

    [SameObject] readonly attribute AbortSignal signal;

    undefined abort(optional any reason);
};
