#import <DOM/AbortSignal.idl>

// https://dom.spec.whatwg.org/#interface-abortcontroller
[Exposed=*]
interface AbortController {
    constructor();

    [SameObject] readonly attribute AbortSignal signal;

    undefined abort(optional any reason);
};
