#import <DOM/Node.idl>

// https://dom.spec.whatwg.org/#interface-abstractrange
[Exposed=Window]
interface AbstractRange {
    readonly attribute Node startContainer;
    readonly attribute unsigned long startOffset;
    readonly attribute Node endContainer;
    readonly attribute unsigned long endOffset;
    readonly attribute boolean collapsed;
};
