#import <DOM/Node.idl>
#import <DOM/Element.idl>

// https://dom.spec.whatwg.org/#interface-attr
[Exposed=Window]
interface Attr : Node {
    readonly attribute DOMString? namespaceURI;
    readonly attribute DOMString? prefix;
    readonly attribute DOMString localName;
    readonly attribute DOMString name;
    [CEReactions] attribute DOMString value;

    readonly attribute Element? ownerElement;

    readonly attribute boolean specified; // useless; always returns true
};
