module Web::Bindings;

import "DOM.idl";
import "LibWeb/DOM/CharacterData.h";

interface CharacterData : Node {

    attribute DOMString data;
    readonly attribute unsigned long length;

    readonly attribute Element? nextElementSibling;
    readonly attribute Element? previousElementSibling;

};
