module Web::Bindings;

import "DOM.idl";
import "LibWeb/DOM/DocumentType.h";

interface DocumentType : Node {

    readonly attribute DOMString name;
    readonly attribute DOMString publicId;
    readonly attribute DOMString systemId;

};
