#import <CSS/StyleSheetList.idl>

// https://dom.spec.whatwg.org/#documentorshadowroot
interface mixin DocumentOrShadowRoot {
    // https://w3c.github.io/csswg-drafts/cssom/#extensions-to-the-document-or-shadow-root-interface
    [SameObject, ImplementedAs=style_sheets_for_bindings] readonly attribute StyleSheetList styleSheets;
    attribute any adoptedStyleSheets;

    // https://www.w3.org/TR/web-animations-1/#extensions-to-the-documentorshadowroot-interface-mixin
    sequence<Animation> getAnimations();
};
