module Web::Bindings;

import "DOM.idl";
import "LibWeb/DOM/DOMImplementation.h";

interface DOMImplementation {

    Document createHTMLDocument(optional DOMString title);

    boolean hasFeature();

};
