// https://dom.spec.whatwg.org/#interface-domtokenlist
[Exposed=Window]
interface DOMTokenList {
    readonly attribute unsigned long length;
    getter DOMString? item(unsigned long index);
    boolean contains(DOMString token);
    [CEReactions] undefined add(DOMString... tokens);
    [CEReactions] undefined remove(DOMString... tokens);
    [CEReactions] boolean toggle(DOMString token, optional boolean force);
    [CEReactions] boolean replace(DOMString token, DOMString newToken);
    boolean supports(DOMString token);
    [CEReactions] stringifier attribute DOMString value;
    iterable<DOMString>;
};
