interface Element : Node {
    readonly attribute DOMString? namespaceURI;
    readonly attribute DOMString tagName;

    DOMString? getAttribute(DOMString qualifiedName);
    undefined setAttribute(DOMString qualifiedName, DOMString value);
    undefined removeAttribute(DOMString qualifiedName);
    boolean hasAttribute(DOMString qualifiedName);
    boolean hasAttributes();

    ArrayFromVector getElementsByTagName(DOMString tagName);
    ArrayFromVector getElementsByClassName(DOMString className);

    readonly attribute Element? firstElementChild;
    readonly attribute Element? lastElementChild;

    Element? querySelector(DOMString selectors);
    ArrayFromVector querySelectorAll(DOMString selectors);

    [LegacyNullToEmptyString] attribute DOMString innerHTML;
    [Reflect] attribute DOMString id;
    [Reflect=class] attribute DOMString className;

    readonly attribute Element? nextElementSibling;
    readonly attribute Element? previousElementSibling;

    [ImplementedAs=style_for_bindings] readonly attribute CSSStyleDeclaration style;
};
