interface Element : Node {
    readonly attribute DOMString? namespaceURI;
    readonly attribute DOMString tagName;

    boolean hasAttributes();
    readonly attribute NamedNodeMap attributes;
    sequence<DOMString> getAttributeNames();
    DOMString? getAttribute(DOMString qualifiedName);
    DOMString? getAttributeNS(DOMString? namespace, DOMString localName);
    undefined setAttribute(DOMString qualifiedName, DOMString value);
    undefined setAttributeNS(DOMString? namespace, DOMString qualifiedName, DOMString value);
    undefined removeAttribute(DOMString qualifiedName);
    undefined removeAttributeNS(DOMString? namespace, DOMString localName);
    boolean toggleAttribute(DOMString qualifiedName, optional boolean force);
    boolean hasAttribute(DOMString qualifiedName);
    boolean hasAttributeNS(DOMString? namespace, DOMString localName);

    Attr? getAttributeNode(DOMString qualifiedName);
    Attr? getAttributeNodeNS(DOMString? namespace, DOMString localName);
    Attr? setAttributeNode(Attr attr);
    Attr? setAttributeNodeNS(Attr attr);
    Attr removeAttributeNode(Attr attr);

    // FIXME: These should return https://dom.spec.whatwg.org/#htmlcollection, but a sequence is essentially equivalent.
    sequence<Element> getElementsByTagName(DOMString tagName);
    sequence<Element> getElementsByClassName(DOMString className);

    [LegacyNullToEmptyString] attribute DOMString innerHTML;
    [Reflect] attribute DOMString id;
    [Reflect=class] attribute DOMString className;

    readonly attribute Element? nextElementSibling;
    readonly attribute Element? previousElementSibling;

    [ImplementedAs=style_for_bindings] readonly attribute CSSStyleDeclaration style;

    // FIXME: These should all come from a ParentNode mixin
    readonly attribute Element? firstElementChild;
    readonly attribute Element? lastElementChild;
    readonly attribute unsigned long childElementCount;

    Element? querySelector(DOMString selectors);
    // FIXME: This should return https://dom.spec.whatwg.org/#nodelist, but a sequence is essentially equivalent.
    sequence<Node> querySelectorAll(DOMString selectors);
};
