module Web::Bindings;

import "DOM.idl";
import "LibWeb/DOM/EventTarget.h";

interface EventTarget {

    undefined addEventListener(DOMString type, EventListener? callback);
    undefined removeEventListener(DOMString type, EventListener? callback);

};
