interface EventTarget {

    // FIXME: Both of these should take in options
    undefined addEventListener(DOMString type, EventListener? callback, optional boolean useCapture = false);
    undefined removeEventListener(DOMString type, EventListener? callback, optional boolean useCapture = false);

    [ImplementedAs=dispatch_event_binding] boolean dispatchEvent(Event event);

};
