#import <DOM/Element.idl>

[Exposed=Window, LegacyUnenumerableNamedProperties, UseNewAKString]
interface HTMLCollection {

    readonly attribute unsigned long length;
    getter Element? item(unsigned long index);
    getter Element? namedItem(DOMString name);

};
