#import <DOM/Node.idl>
#import <DOM/NodeList.idl>

// https://dom.spec.whatwg.org/#interface-mutationrecord
[Exposed=Window]
interface MutationRecord {
    readonly attribute DOMString type;
    [SameObject] readonly attribute Node target;
    [SameObject] readonly attribute NodeList addedNodes;
    [SameObject] readonly attribute NodeList removedNodes;
    readonly attribute Node? previousSibling;
    readonly attribute Node? nextSibling;
    readonly attribute DOMString? attributeName;
    readonly attribute DOMString? attributeNamespace;
    readonly attribute DOMString? oldValue;
};
