#import <DOM/Attr.idl>

[Exposed=Window, LegacyUnenumerableNamedProperties, UseDeprecatedAKString]
interface NamedNodeMap {
    readonly attribute unsigned long length;

    getter Attr? item(unsigned long index);
    getter Attr? getNamedItem(DOMString qualifiedName);
    Attr? getNamedItemNS(DOMString? namespace, DOMString localName);

    [CEReactions] Attr? setNamedItem(Attr attr);
    [CEReactions] Attr? setNamedItemNS(Attr attr);

    [CEReactions] Attr removeNamedItem(DOMString qualifiedName);
    [CEReactions] Attr removeNamedItemNS(DOMString? namespace, DOMString localName);
};
