interface Node : EventTarget {

    readonly attribute unsigned short nodeType;
    readonly attribute DOMString nodeName;

    boolean hasChildNodes();
    // FIXME: This should be a NodeList
    readonly attribute ArrayFromVector childNodes;
    readonly attribute Node? firstChild;
    readonly attribute Node? lastChild;
    readonly attribute Node? previousSibling;
    readonly attribute Node? nextSibling;
    readonly attribute Node? parentNode;
    readonly attribute Element? parentElement;
    attribute DOMString textContent;

    Node appendChild(Node node);
    Node insertBefore(Node node, Node? child);
    Node removeChild(Node child);

    const unsigned short ELEMENT_NODE = 1;
    const unsigned short ATTRIBUTE_NODE = 2;
    const unsigned short TEXT_NODE = 3;
    const unsigned short CDATA_SECTION_NODE = 4;
    const unsigned short ENTITY_REFERENCE_NODE = 5;
    const unsigned short ENTITY_NODE = 6;
    const unsigned short PROCESSING_INSTRUCTION_NODE = 7;
    const unsigned short COMMENT_NODE = 8;
    const unsigned short DOCUMENT_NODE = 9;
    const unsigned short DOCUMENT_TYPE_NODE = 10;
    const unsigned short DOCUMENT_FRAGMENT_NODE = 11;
    const unsigned short NOTATION_NODE = 12;

};
