#import <DOM/Node.idl>
#import <DOM/NodeFilter.idl>

// https://dom.spec.whatwg.org/#interface-nodeiterator
[Exposed=Window]
interface NodeIterator {
    [SameObject] readonly attribute Node root;
    readonly attribute Node referenceNode;
    readonly attribute boolean pointerBeforeReferenceNode;
    readonly attribute unsigned long whatToShow;
    readonly attribute NodeFilter? filter;

    Node? nextNode();
    Node? previousNode();

    undefined detach();
};
