#import <DOM/Node.idl>

// https://dom.spec.whatwg.org/#interface-nodelist
[Exposed=Window]
interface NodeList {
    getter Node? item(unsigned long index);
    readonly attribute unsigned long length;
    iterable<Node>;
};
