#import <DOM/Document.idl>
#import <DOM/Element.idl>
#import <DOM/EventTarget.idl>

// https://dom.spec.whatwg.org/#node
[Exposed=Window]
interface Node : EventTarget {
    const unsigned short ELEMENT_NODE = 1;
    const unsigned short ATTRIBUTE_NODE = 2;
    const unsigned short TEXT_NODE = 3;
    const unsigned short CDATA_SECTION_NODE = 4;
    const unsigned short ENTITY_REFERENCE_NODE = 5; // legacy
    const unsigned short ENTITY_NODE = 6; // legacy
    const unsigned short PROCESSING_INSTRUCTION_NODE = 7;
    const unsigned short COMMENT_NODE = 8;
    const unsigned short DOCUMENT_NODE = 9;
    const unsigned short DOCUMENT_TYPE_NODE = 10;
    const unsigned short DOCUMENT_FRAGMENT_NODE = 11;
    const unsigned short NOTATION_NODE = 12; // legacy
    readonly attribute unsigned short nodeType;
    readonly attribute DOMString nodeName;

    readonly attribute USVString baseURI;

    readonly attribute boolean isConnected;
    readonly attribute Document? ownerDocument;
    Node getRootNode(optional GetRootNodeOptions options = {});
    readonly attribute Node? parentNode;
    readonly attribute Element? parentElement;
    boolean hasChildNodes();
    [SameObject] readonly attribute NodeList childNodes;
    readonly attribute Node? firstChild;
    readonly attribute Node? lastChild;
    readonly attribute Node? previousSibling;
    readonly attribute Node? nextSibling;

    [CEReactions] attribute DOMString? nodeValue;
    // FIXME: [LegacyNullToEmptyString] is not allowed on nullable types as per the Web IDL spec.
    //        However, we only apply it to setters, so this works as a stop gap.
    //        Replace this with something like a special cased [LegacyNullToEmptyString].
    [LegacyNullToEmptyString, CEReactions] attribute DOMString? textContent;
    [CEReactions] undefined normalize();

    [ImplementedAs=clone_node_binding, CEReactions] Node cloneNode(optional boolean deep = false);
    boolean isEqualNode(Node? otherNode);
    boolean isSameNode(Node? otherNode); // legacy alias of ===

    const unsigned short DOCUMENT_POSITION_DISCONNECTED = 0x01;
    const unsigned short DOCUMENT_POSITION_PRECEDING = 0x02;
    const unsigned short DOCUMENT_POSITION_FOLLOWING = 0x04;
    const unsigned short DOCUMENT_POSITION_CONTAINS = 0x08;
    const unsigned short DOCUMENT_POSITION_CONTAINED_BY = 0x10;
    const unsigned short DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = 0x20;
    unsigned short compareDocumentPosition(Node? otherNode);
    boolean contains(Node? other);

    DOMString? lookupPrefix(DOMString? namespace);
    DOMString? lookupNamespaceURI(DOMString? prefix);
    boolean isDefaultNamespace(DOMString? namespace);

    [ImplementedAs=pre_insert, CEReactions] Node insertBefore(Node node, Node? child);
    [CEReactions] Node appendChild(Node node);
    [CEReactions] Node replaceChild(Node node, Node child);
    [ImplementedAs=pre_remove, CEReactions] Node removeChild(Node child);
};

dictionary GetRootNodeOptions {
    boolean composed = false;
};
