#import <DOM/HTMLCollection.idl>
#import <DOM/Node.idl>

// https://dom.spec.whatwg.org/#parentnode
interface mixin ParentNode {
    [SameObject] readonly attribute HTMLCollection children;
    readonly attribute Element? firstElementChild;
    readonly attribute Element? lastElementChild;
    readonly attribute unsigned long childElementCount;

    [CEReactions, Unscopable] undefined prepend((Node or DOMString)... nodes);
    [CEReactions, Unscopable] undefined append((Node or DOMString)... nodes);
    [CEReactions, Unscopable] undefined replaceChildren((Node or DOMString)... nodes);

    Element? querySelector(DOMString selectors);
    [NewObject] NodeList querySelectorAll(DOMString selectors);
};
