#import <DOM/Node.idl>
#import <DOM/AbstractRange.idl>

[Exposed=Window]
interface Range : AbstractRange {

    constructor();

    readonly attribute Node commonAncestorContainer;

    undefined setStart(Node node, unsigned long offset);
    undefined setEnd(Node node, unsigned long offset);
    undefined setStartBefore(Node node);
    undefined setStartAfter(Node node);
    undefined setEndBefore(Node node);
    undefined setEndAfter(Node node);

    Range cloneRange();

};
