#import <DOM/DocumentFragment.idl>

interface ShadowRoot : DocumentFragment {

    readonly attribute DOMString mode;
    readonly attribute Element host;

    // FIXME: This should come from a InnerHTML mixin.
    [LegacyNullToEmptyString] attribute DOMString innerHTML;

};
