module Web::Bindings;

import "../Bindings/LibWeb.idl";
import "LibWeb/DOM/ShadowRoot.h";

interface ShadowRoot : DocumentFragment {

    readonly attribute DOMString mode;
    readonly attribute Element host;

};
