#import <DOM/Node.idl>
#import <DOM/AbstractRange.idl>

// https://dom.spec.whatwg.org/#dictdef-staticrangeinit
dictionary StaticRangeInit {
    required Node startContainer;
    required unsigned long startOffset;
    required Node endContainer;
    required unsigned long endOffset;
};

// https://dom.spec.whatwg.org/#staticrange
[Exposed=Window]
interface StaticRange : AbstractRange {
    constructor(StaticRangeInit init);
};
