#import <DOM/Node.idl>
#import <DOM/AbstractRange.idl>

[Exposed=Window, NoInstanceWrapper]
interface StaticRange : AbstractRange {
    constructor(StaticRangeInit init);
};

dictionary StaticRangeInit {
    required Node startContainer;
    required unsigned long startOffset;
    required Node endContainer;
    required unsigned long endOffset;
};
