#import <DOM/CharacterData.idl>

// https://dom.spec.whatwg.org/#text
[Exposed=Window]
interface Text : CharacterData {
    constructor(optional DOMString data = "");

    [NewObject] Text splitText(unsigned long offset);

};
