#import <DOM/Node.idl>
#import <DOM/NodeFilter.idl>

[Exposed=Window, NoInstanceWrapper]
interface TreeWalker {

    [SameObject] readonly attribute Node root;
    readonly attribute unsigned long whatToShow;
    readonly attribute NodeFilter? filter;
    attribute Node currentNode;

    Node? parentNode();
    Node? firstChild();
    Node? lastChild();
    Node? previousSibling();
    Node? nextSibling();
    Node? previousNode();
    Node? nextNode();

};
