#import <PerformanceTimeline/PerformanceEntry.idl>

// https://w3c.github.io/user-timing/#performancemeasure
[Exposed=(Window,Worker)]
interface PerformanceMeasure : PerformanceEntry {
    readonly attribute any detail;
};

// https://w3c.github.io/user-timing/#extensions-performance-interface
dictionary PerformanceMeasureOptions {
    any detail;
    (DOMString or DOMHighResTimeStamp) start;
    DOMHighResTimeStamp duration;
    (DOMString or DOMHighResTimeStamp) end;
};
