[Exposed=(Window,Worker)]
interface TextEncoder {
    constructor();

    [NewObject] Uint8Array encode(optional USVString input = "");
    // TextEncoderEncodeIntoResult encodeInto(USVString source, [AllowShared] Uint8Array destination);

    readonly attribute DOMString encoding;
};
