OBJS = \
    ../../AK/JsonPathElement.o \
    ../../AK/StreamJsonBuilder.o \
    ../../AK/StreamJsonParser.o \
    DisassemblyModel.o \
    Profile.o \
    ProfileModel.o \
    ProfileTimelineWidget.o \
    main.o

PROGRAM = ProfileViewer

LIB_DEPS = GUI Gfx IPC Core X86

include ../../Makefile.common
