#import <DOM/Event.idl>

interface ProgressEvent : Event {
    constructor(DOMString type, optional ProgressEventInit eventInitDict = {});

    readonly attribute boolean lengthComputable;
    readonly attribute unsigned long loaded;
    readonly attribute unsigned long total;
};

dictionary ProgressEventInit : EventInit {
    boolean lengthComputable = false;
    unsigned long loaded = 0;
    unsigned long total = 0;
};
