#import <XHR/XMLHttpRequestEventTarget.idl>

// https://xhr.spec.whatwg.org/#xmlhttprequestupload
[Exposed=(Window,DedicatedWorker,SharedWorker)]
interface XMLHttpRequestUpload : XMLHttpRequestEventTarget {
};
