#import <DOM/EventTarget.idl>
#import <DOM/EventHandler.idl>

// https://xhr.spec.whatwg.org/#xmlhttprequesteventtarget
[Exposed=(Window,DedicatedWorker,SharedWorker)]
interface XMLHttpRequestEventTarget : EventTarget {

    // event handlers
    attribute EventHandler onloadstart;
    attribute EventHandler onprogress;
    attribute EventHandler onabort;
    attribute EventHandler onerror;
    attribute EventHandler onload;
    attribute EventHandler ontimeout;
    attribute EventHandler onloadend;

};
