OBJS = \
    AudioEngine.o \
    MainWidget.o \
    WaveWidget.o \
    RollWidget.o \
    SamplerWidget.o \
    KeysWidget.o \
    KnobsWidget.o \
    main.o

PROGRAM = Piano

LIB_DEPS = GUI Gfx Audio IPC Thread Pthread Core

include ../../Makefile.common
