#!sh

alias fm=FileManager
alias mag=Magnifier
alias sh=Shell
alias tb=Taskbar
alias te=TextEditor
alias he=HexEditor
alias pp=PixelPaint
alias iv=ImageViewer
alias pi=Piano
alias calc=Calculator
alias calendar=Calendar
alias sp=SoundPlayer
alias help=Help
alias br=Browser
alias hs=HackStudio
alias sdb=Debugger
alias sm=SystemMonitor
alias pv=Profiler
alias ws=WebServer
alias fe=FontEditor
alias ss=Spreadsheet
alias vp=VideoPlayer

alias ll='ls -l'

if [ "$(id -u)" = "0" ]; then
    prompt_color=31
else
    prompt_color=32
fi

export PROMPT="\\X\\u@\\h:\\w\\a\\e[$prompt_color;1m\\h\\e[0m:\\e[34;1m\\w\\e[0m \\p "
export TMPDIR=/tmp

PROGRAMS_ALLOWED_TO_MODIFY_DEFAULT_TERMIOS="stty"
