#!sh

alias fm=FileManager
alias irc=IRCClient
alias ms=Minesweeper
alias sh=Shell
alias sn=Snake
alias tb=Taskbar
alias wg=WidgetGallery
alias te=TextEditor
alias he=HexEditor
alias pp=PixelPaint
alias qs=QuickShow
alias pi=Piano
alias calc=Calculator
alias calendar=Calendar
alias ins=Inspector
alias sp=SoundPlayer
alias help=Help
alias br=Browser
alias hs=HackStudio
alias sdb=Debugger
alias sm=SystemMonitor
alias pv=Profiler
alias ws=WebServer
alias sl=Solitaire
alias ue=UserspaceEmulator
alias welcome=Serendipity

alias ll='ls -l'

export PROMPT="\\X\\u@\\h:\\w\\a\\e[32;1m@\\h\\e[0m:\\e[34;1m\\w\\e[0m \\p "
