#!sh

alias fm=FileManager
alias hw=HelloWorld
alias irc=IRCClient
alias ms=Minesweeper
alias sh=Shell
alias sn=Snake
alias tb=Taskbar
alias wg=WidgetGallery
alias te=TextEditor
alias he=HexEditor
alias pp=PixelPaint
alias qs=QuickShow
alias pi=Piano
alias calc=Calculator
alias calendar=Calendar
alias ins=Inspector
alias sp=SoundPlayer
alias help=Help
alias br=Browser
alias hs=HackStudio
alias sdb=Debugger
alias sm=SystemMonitor
alias pv=Profiler
alias ws=WebServer
alias sl=Solitaire
alias wv=WebView
alias ue=UserspaceEmulator

alias ll='ls -l'
