#!sh

alias fm=FileManager
alias mag=Magnifier
alias sh=Shell
alias tb=Taskbar
alias te=TextEditor
alias he=HexEditor
alias pp=PixelPaint
alias iv=ImageViewer
alias pi=Piano
alias calc=Calculator
alias calendar=Calendar
alias sp=SoundPlayer
alias help=Help
alias br=Browser
alias hs=HackStudio
alias sdb=Debugger
alias sm=SystemMonitor
alias pv=Profiler
alias ws=WebServer
alias fe=FontEditor
alias ss=Spreadsheet
alias vp=VideoPlayer

alias ll='ls -l'
alias poweroff='shutdown'

if [ "$(id -u)" = "0" ] {
    prompt_color=31
} else {
    prompt_color=32
}

export PROMPT="\\X\\u@\\h:\\w\\a\\e[$prompt_color;1m\\h\\e[0m:\\e[34;1m\\w\\e[0m \\p "

export HISTORY_AUTOSAVE_TIME_MS=10000

export TMPDIR=/tmp

PROGRAMS_ALLOWED_TO_MODIFY_DEFAULT_TERMIOS=(stty)

for /usr/share/shell/completion/*.sh { source $it }
