#import <StorageAPI/StorageManager.idl>

// https://storage.spec.whatwg.org/#navigatorstorage
[SecureContext]
interface mixin NavigatorStorage {
    [SameObject] readonly attribute StorageManager storage;
};
