// https://w3c.github.io/IndexedDB/#idbfactory
[Exposed=(Window,Worker)]
interface IDBFactory {
    [FIXME, NewObject] IDBOpenDBRequest open(DOMString name,
                                             optional [EnforceRange] unsigned long long version);
    [FIXME, NewObject] IDBOpenDBRequest deleteDatabase(DOMString name);

    [FIXME] Promise<sequence<IDBDatabaseInfo>> databases();

    [FIXME] short cmp(any first, any second);
};

dictionary IDBDatabaseInfo {
    DOMString name;
    unsigned long long version;
};
