#import <HTML/CanvasGradient.idl>

// https://html.spec.whatwg.org/multipage/canvas.html#canvasfillstrokestyles
interface mixin CanvasFillStrokeStyles {
    // FIXME: Should be `(DOMString or CanvasGradient or CanvasPattern)`
    attribute DOMString strokeStyle;
    // FIXME: Should be `(DOMString or CanvasGradient or CanvasPattern)`
    attribute DOMString fillStyle;
    CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);
    CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);
    CanvasGradient createConicGradient(double startAngle, double x, double y);
    // FIXME: CanvasPattern? createPattern(CanvasImageSource image, [LegacyNullToEmptyString] DOMString repetition);
};
