OBJS = \
    ManualModel.o \
    ManualSectionNode.o \
    ManualPageNode.o \
    History.o \
    main.o

PROGRAM = Help

LIB_DEPS = GUI HTML Gfx Markdown IPC Protocol Thread Pthread Core

include ../../Makefile.common
