interface DocumentFragment : Node {

    Element? getElementById(DOMString id);

    readonly attribute Element? firstElementChild;
    readonly attribute Element? lastElementChild;

    Element? querySelector(DOMString selectors);
    ArrayFromVector querySelectorAll(DOMString selectors);

}
