interface Element : Node {

    readonly attribute DOMString tagName;

    DOMString? getAttribute(DOMString qualifiedName);
    void setAttribute(DOMString qualifiedName, DOMString value);

    attribute DOMString innerHTML;
    [Reflect] attribute DOMString id;
    [Reflect=class] attribute DOMString className;

}

