#import <DOM/EventTarget.idl>

// FIXME: typedef sequence<ClipboardItem> ClipboardItems;

// https://w3c.github.io/clipboard-apis/#clipboard
[SecureContext, Exposed=Window]
interface Clipboard : EventTarget {
    [FIXME] Promise<ClipboardItems> read();
    [FIXME] Promise<DOMString> readText();
    [FIXME] Promise<undefined> write(ClipboardItems data);
    Promise<undefined> writeText(DOMString data);
};
