interface URL {
    constructor(USVString url, optional USVString base);

    stringifier attribute USVString href;
    readonly attribute USVString origin;
    // TODO: attribute USVString protocol;
    attribute USVString username;
    attribute USVString password;
    // TODO: attribute USVString host;
    // TODO: attribute USVString hostname;
    // TODO: attribute USVString port;
    // TODO: attribute USVString pathname;
    // TODO: attribute USVString search;
    [SameObject] readonly attribute URLSearchParams searchParams;
    // TODO: attribute USVString hash;

    USVString toJSON();
};
