interface URLSearchParams {

  // FIXME: the real type of init is (sequence<sequence<USVString>> or record<USVString, USVString> or USVString)
  constructor(optional USVString init = "");

  undefined append(USVString name, USVString value);
  undefined delete(USVString name);
  USVString? get(USVString name);
  // TODO: sequence<USVString> getAll(USVString name);
  boolean has(USVString name);
  undefined set(USVString name, USVString value);

  undefined sort();

  // TODO: iterable<USVString, USVString>;
  stringifier;
};
