include ../../Makefile.common

OBJS = \
    PaintableWidget.o \
    PaletteWidget.o \
    ToolboxWidget.o \
    Tool.o \
    PenTool.o \
    LineTool.o \
    EraseTool.o \
    BucketTool.o \
    ColorDialog.o \
    SprayTool.o \
    PickerTool.o \
    main.o

APP = PaintBrush

include ../Makefile.common
