OBJS = \
    PaintableWidget.o \
    PaletteWidget.o \
    ToolboxWidget.o \
    Tool.o \
    PenTool.o \
    LineTool.o \
    RectangleTool.o \
    EllipseTool.o \
    EraseTool.o \
    BucketTool.o \
    ColorDialog.o \
    SprayTool.o \
    PickerTool.o \
    main.o

PROGRAM = PaintBrush

LIB_DEPS = GUI Draw IPC Thread Pthread Core

include ../../Makefile.common
