OBJS = \
    PaintableWidget.o \
    PaletteWidget.o \
    ToolboxWidget.o \
    Tool.o \
    PenTool.o \
    LineTool.o \
    EraseTool.o \
    BucketTool.o \
    ColorDialog.o \
    SprayTool.o \
    PickerTool.o \
    main.o

PROGRAM = PaintBrush

LDFLAGS = -lgui -ldraw -lipc -lthread -lpthread -lcore -lc

include ../../Makefile.common
